### ISSUE TITLE
Shell scrit invocation error

### ISSUE THREAD

**Issue by SergioMejiaAragon** [quikkly/ios-sdk#1]
After install and build the project

Quikkly.framework/
Quikkly.framework/Assets.car
Quikkly.framework/Default-Blueprint.json
Quikkly.framework/Info.plist
Quikkly.framework/Quikkly

sent 13388348 bytes  received 114 bytes  26776924.00 bytes/sec
total size is 13386361  speedup is 1.00
fatal error: lipo: -remove's specified would result in an empty fat file

swift 3.1
ios 10.0

**Comment by phedoreanu** [comment]
@greggnogg-quikkly @juxs ?

**Comment by greggnogg-quikkly** [comment]
Thanks for raising this we're looking into it.

**Comment by greggnogg-quikkly** [comment]
This should be fixed in the latest SDK, which has XCode 9 Support
