### ISSUE TITLE
XCFramework Authentication Failing

### ISSUE THREAD

**Issue by dlallie** [quikkly/ios-sdk#17]
When using the most recent XCFramework code scanning from a camera feed does not work at all. No delegate methods are called and neither are any scanning errors reported anywhere.

I am using the `ScanView` class and the camera feed displays correctly, it just seems that the scanning has some sort of error.

When I first noticed this issue I saw some log error messages which seemed to suggest the SDK was failing it's authentication but I haven't been able to reproduce this error message again.

**Comment by janekp** [comment]
Try adding "@objc" in-front of delegate method(s)

`@objc func scanView(_ scanView: ScanView, didDetectScannables scannables: [Scannable])`

**Comment by dlallie** [comment]
That still doesn't work for me unfortunately.

When retesting I did see this error message in the Xcode console:
```
Task <0A43CB90-23EE-4F38-A4D4-B4C55D1FF23E>.<1> finished with error [-1003] Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found." UserInfo={NSUnderlyingError=0x2825c5ce0 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://api.quikkly.io/gapi/authorize, NSErrorFailingURLKey=https://api.quikkly.io/gapi/authorize, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=A server with the specified hostname could not be found.}
```

**Comment by janekp** [comment]
Fortunately, that line is not causing issues. There was one issue with blueprints that I tweaked (https://github.com/quikkly/ios-sdk/commit/6452d735f59086ab1e4810e1512cfd5a5ac1a412 ). Apple changed something and ran into problems with the latest iOS. PS! I had to delete .xcframework from the project and re-add the updated one, because of XCode caching issues.

**Comment by dlallie** [comment]
Sorry, I hadn't seen a new XCFramework committed a couple of days ago

I've tried that version in my project and everything is working now. Thanks for your help! 🙂

**Comment by obuseme** [comment]
I'm seeing the error `A server with the specified hostname could not be found.` for `https://api.quikkly.io/gapi/authorize` as well - is that something I should be concerned with?
