### ISSUE TITLE
Cannot Compile with Quikkly framework after upgrading to XCode Version 11.4 (11E146)

### ISSUE THREAD

**Issue by williamrct** [quikkly/ios-sdk#19]
After upgrading to Xcode Version 11.4 (11E146)
I now get these compile errors...

Swift Compiler Error Group
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:12:52: 'ScanView' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:12:103: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:20:43: 'ScanViewDelegate' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:51:38: 'ScannableSkin' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:53:37: 'ScannableSkin' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:54:41: 'QKScannableSkinJoinOption' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:64:41: 'Quikkly' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:77:78: 'ScannableView' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:78:62: 'ScannableView' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:81:43: 'ScannableViewDelegate' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:82:39: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:83:11: '@objc' getter for non-'@objc' property
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:84:11: '@objc' setter for non-'@objc' property
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:87:66: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:102:113: 'UIImageColors' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:103:86: 'UIImageColors' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:119:85: 'ScannablePipelineResult' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:119:131: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:122:43: 'ScannablePipelineDelegate' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:123:72: 'ScannablePipelineResult' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:123:106: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:130:71: 'ScanViewDelegate' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:163:34: 'ScannableSkin' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:171:103: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:172:83: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:173:121: 'ScannableSkin' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:173:180: 'Scannable' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:174:103: 'ScannableSkin' is not a member type of 'Quikkly'
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/Frameworks/Quikkly.framework/Modules/Quikkly.swiftmodule/arm64-apple-ios.swiftinterface:58:31: 'Quikkly' declared here
/Users/WI027RO/Library/Mobile Documents/com~apple~CloudDocs/projects/FollowMe_20191102/FollowMe/SharedInstances/FMMScanCode.swift:10:8: Failed to load module 'Quikkly'

**Comment by janekp** [comment]
Please try again (3.4.19). Nothing was changed. Just recompiled with XCode 11.4

**Comment by williamrct** [comment]
The work around for this issue is described in the link that follows:

https://forums.developer.apple.com/thread/123253
