### ISSUE TITLE
Not working on Xcode9

### ISSUE THREAD

**Issue by bakjos** [quikkly/ios-sdk#3]
It shows an error when it tries to compile: "Module compiled with Swift 3.1 cannot be imported in Swift 3.2: /Quikkly.framework/Modules/Quikkly.swiftmodule/arm64.swiftmodule"

**Comment by ufuf** [comment]
I got it working with this so post:
https://stackoverflow.com/a/44415247

Basicly adding config.build_settings['SWIFT_VERSION'] = '3.2' to pod file seems enough.

**Comment by bakjos** [comment]
Thanks, it seems like it's working well now
